### ISSUE TITLE
Can't Add Redirects in Production

### ISSUE THREAD

**Issue by steven-dyson** [Webbist-dev/strapi-redirects#21]
I get this error when I try to add redirects. However, it works on my local.

```
[2024-05-30 21:43:33.960] error: Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
at validateRedirect (/home/ubuntu/cms-web/node_modules/strapi-plugin-redirects/server/helpers/redirectValidationHelper.js:48:23)
at Object.create (/home/ubuntu/cms-web/node_modules/strapi-plugin-redirects/server/services/redirects.js:63:28)
at Object.create (/home/ubuntu/cms-web/node_modules/strapi-plugin-redirects/server/controllers/redirects.js:13:52)
at dispatch (/home/ubuntu/cms-web/node_modules/koa-compose/index.js:42:32)
at returnBodyMiddleware (/home/ubuntu/cms-web/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:24)
at dispatch (/home/ubuntu/cms-web/node_modules/koa-compose/index.js:42:32)
at policiesMiddleware (/home/ubuntu/cms-web/node_modules/@strapi/strapi/dist/services/server/policy.js:15:11)
at dispatch (/home/ubuntu/cms-web/node_modules/koa-compose/index.js:42:32)
at /home/ubuntu/cms-web/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:18
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-30 21:43:33.961] http: POST /redirects (120 ms) 500
```

**Comment by Webbist-dev** [comment]
Ah the elusive works on local but not on production. 
Did you fix this or can you provide more information? Looks like the bug is coming from the redirect validation, no id. I'd imagine you have some weird data, did you do a data transfer for the DB or is this a fresh DB on production?

**Comment by steven-dyson** [comment]
@Webbist-dev Looks like I just need to remove the plugin, build, and then add the plugin back. All good now!
